#ifndef KERN_VM_ERROR_CODES_HPP
#define KERN_VM_ERROR_CODES_HPP

namespace kern {

enum class VMErrorCode : int {
    NONE = 0,

    // browserKit
    BROWSERKIT_INIT_FAIL = 1001,
    BROWSERKIT_RENDER_FAIL = 1002,
    BROWSERKIT_UNSUPPORTED = 1003,
    BROWSERKIT_PROTOCOL_ERROR = 1004,
    BROWSERKIT_SANDBOX_DENY = 1005,
    BROWSERKIT_NOT_IMPLEMENTED = 1006,
    BROWSERKIT_WS_NOT_CONNECTED = 1007,
    BROWSERKIT_PROTOCOL_INVALID = 1008,

    // import
    IMPORT_NOT_FOUND = 2001,
    IMPORT_CYCLE = 2002,
    IMPORT_INVALID_PATH = 2003,
    IMPORT_READ_FAIL = 2004,
    IMPORT_INTERNAL = 2005,
    IMPORT_UNSUPPORTED_MODULE = 2006,

    // vM/core
    STACK_UNDERFLOW = 3001,
    STACK_OVERFLOW = 3011,
    STEP_LIMIT_EXCEEDED = 3002,
    INVALID_OPERATION = 3012,
    RETURN_OUTSIDE_FUNCTION = 3003,
    INVALID_JUMP_TARGET = 3004,
    INVALID_BYTECODE = 3005,
    INVALID_CALL_TARGET = 3006,
    DIVISION_BY_ZERO = 3008,
    PERMISSION_DENIED = 3009,
    /** Abstract stack depth differs on merge at the same PC (control-flow inconsistency). */
    BYTECODE_VERIFY_STACK = 3010,
};

} // namespace kern

#endif // kERN_VM_ERROR_CODES_HPP
