#ifndef KERN_STDLIB_STDV1_EXPORTS_HPP
#define KERN_STDLIB_STDV1_EXPORTS_HPP

#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

namespace kern {

/* * User-facing export name -> global builtin name (std_math_* or legacy read_file, etc.).*/
inline const std::unordered_map<std::string, std::vector<std::pair<std::string, std::string>>>& stdV1NamedExports() {
    static const std::unordered_map<std::string, std::vector<std::pair<std::string, std::string>>> m = {
        {"std.v1.math",
            {{"fmod", "std_math_fmod"},
             {"hypot", "std_math_hypot"},
             {"log10", "std_math_log10"},
             {"log2", "std_math_log2"},
             {"exp", "std_math_exp"},
             {"expm1", "std_math_expm1"},
             {"log1p", "std_math_log1p"},
             {"cbrt", "std_math_cbrt"},
             {"asin", "std_math_asin"},
             {"acos", "std_math_acos"},
             {"atan", "std_math_atan"},
             {"sinh", "std_math_sinh"},
             {"cosh", "std_math_cosh"},
             {"tanh", "std_math_tanh"},
             {"copysign", "std_math_copysign"},
             {"nextafter", "std_math_nextafter"},
             {"trunc", "std_math_trunc"},
             {"round_to_int", "std_math_round_to_int"}}},
        {"std.v1.string",
            {{"index_of", "std_string_index_of"},
             {"last_index_of", "std_string_last_index_of"},
             {"count_substr", "std_string_count_substr"},
             {"substr", "std_string_substr"},
             {"equals_ignore_case", "std_string_equals_ignore_case"},
             {"compare", "std_string_compare"},
             {"trim_left", "std_string_trim_left"},
             {"trim_right", "std_string_trim_right"},
             {"split_first", "std_string_split_first"},
             {"char_at", "std_string_char_at"},
             {"is_empty", "std_string_is_empty"},
             {"remove_prefix", "std_string_remove_prefix"},
             {"remove_suffix", "std_string_remove_suffix"},
             {"pad_center", "std_string_pad_center"}}},
        {"std.v1.bytes",
            {{"crc32", "std_bytes_crc32"},
             {"to_hex", "std_bytes_to_hex"},
             {"from_hex", "std_bytes_from_hex"},
             {"xor", "std_bytes_xor"},
             {"concat", "std_bytes_concat"},
             {"slice", "std_bytes_slice"},
             {"equal", "std_bytes_equal"},
             {"get_u16_le", "std_bytes_get_u16_le"},
             {"get_u32_le", "std_bytes_get_u32_le"},
             {"set_u32_le", "std_bytes_set_u32_le"},
             {"get_u8", "std_bytes_get_u8"},
             {"from_string", "std_bytes_from_string"},
             {"len", "std_bytes_len"}}},
        {"std.v1.collections",
            {{"array_index_of", "std_col_array_index_of"},
             {"array_last_index_of", "std_col_array_last_index_of"},
             {"swap", "std_col_swap"},
             {"rotate_left", "std_col_rotate_left"},
             {"dict_merge_shallow", "std_col_dict_merge_shallow"},
             {"array_zip_pairs", "std_col_array_zip_pairs"},
             {"array_unique", "std_col_array_unique"},
             {"array_fill", "std_col_array_fill"},
             {"map_invert", "std_col_map_invert"},
             {"array_intersect", "std_col_array_intersect"}}},
        {"std.v1.fs",
            {{"read_text", "read_file"},
             {"write_text", "write_file"},
             {"append_text", "append_file"},
             {"fd_open", "fs_fd_open"},
             {"fd_close", "fs_fd_close"},
             {"fd_read", "fs_fd_read"},
             {"fd_write", "fs_fd_write"},
             {"fd_pread", "fs_fd_pread"},
             {"fd_pwrite", "fs_fd_pwrite"},
             {"flock", "fs_flock"},
             {"statx", "fs_statx"},
             {"atomic_write", "fs_atomic_write"},
             {"watch", "fs_watch"},
             {"space", "fs_space"},
             {"mounts", "fs_mounts"},
             {"file_exists", "fileExists"},
             {"list_dir", "listDir"},
             {"list_recursive", "listDirRecursive"},
             {"is_file", "is_file"},
             {"is_dir", "is_dir"},
             {"create_dir", "create_dir"},
             {"copy_file", "copy_file"},
             {"delete_file", "delete_file"},
             {"move_file", "move_file"},
             {"map_file", "map_file"},
             {"unmap_file", "unmap_file"},
             {"memory_protect", "memory_protect"},
             {"file_size", "file_size"},
             {"glob", "glob"},
             {"path_join", "path_join"},
             {"basename", "basename"},
             {"dirname", "dirname"},
             {"normalize", "path_normalize"},
             {"realpath", "realpath"}}},
        {"std.v1.process",
            {{"cli_args", "cli_args"},
             {"cwd", "cwd"},
             {"chdir", "chdir"},
             {"env_get", "env_get"},
             {"env_all", "env_all"},
             {"env_set", "env_set"},
             {"getpid", "getpid"},
             {"hostname", "hostname"},
             {"cpu_count", "cpu_count"},
             {"which", "which"},
             {"run", "exec_args"},
             {"capture", "exec_capture"},
             {"spawn", "spawn"},
             {"spawn_v2", "process_spawn_v2"},
             {"wait_process", "wait_process"},
             {"wait", "process_wait"},
             {"kill_process", "kill_process"},
             {"kill_tree", "process_kill_tree"},
             {"list", "process_list"},
             {"job_create", "process_job_create"},
             {"job_add", "process_job_add"},
             {"job_kill", "process_job_kill"},
             {"permissions_active", "permissions_active"},
             {"exec_args", "exec_args"},
             {"exec_capture", "exec_capture"},
             {"sleep_ms", "sleep_ms"}}},
        {"std.v1.net",
            {{"http_get", "http_get"},
             {"http_post", "http_post"},
             {"http_request", "http_request"},
             {"url_parse", "url_parse"},
             {"url_encode", "url_encode"},
             {"url_decode", "url_decode"},
             {"parse_query", "parse_query"},
             {"build_query", "build_query"},
             {"merge_query", "merge_query"},
             {"url_resolve", "url_resolve"},
             {"url_normalize", "url_normalize"},
             {"url_path_join", "url_path_join"},
             {"tcp_connect", "tcp_connect"},
             {"tcp_server", "net_tcp_server"},
             {"tcp_listen", "tcp_listen"},
             {"tcp_accept", "tcp_accept"},
             {"tcp_poll", "net_tcp_poll"},
             {"tcp_send", "tcp_send"},
             {"tcp_recv", "tcp_recv"},
             {"tcp_close", "tcp_close"},
             {"dns_lookup", "net_dns_lookup"},
             {"tls_connect", "net_tls_connect"},
             {"ws_connect", "net_ws_connect"},
             {"ws_listen", "net_ws_listen"},
             {"udp_open", "udp_open"},
             {"udp_bind", "udp_bind"},
             {"udp_send", "udp_send"},
             {"udp_recv", "udp_recv"},
             {"udp_close", "udp_close"},
             {"socket_set_nonblocking", "socket_set_nonblocking"},
             {"socket_select_read", "socket_select_read"},
             {"socket_select_write", "socket_select_write"}}},
        {"std.v1.os",
            {{"platform", "platform"},
             {"os_name", "os_name"},
             {"arch", "arch"},
             {"hostname", "hostname"},
             {"cpu_count", "cpu_count"},
             {"getpid", "getpid"},
             {"cwd", "cwd"},
             {"chdir", "chdir"},
             {"temp_dir", "temp_dir"},
             {"realpath", "realpath"},
             {"which", "which"},
             {"runtime_info", "runtime_info"},
             {"runtime_limits", "os_runtime_limits"},
             {"features", "os_features"},
             {"permissions_active", "permissions_active"}}},
        {"std.v1.signal",
            {{"send", "kill_process"},
             {"cancel_process", "kill_process"},
             {"trap", "os_signal_trap"},
             {"untrap", "os_signal_untrap"}}},
        {"std.v1.memory",
            {{"alloc", "alloc"},
             {"free", "free"},
             {"ptr_address", "ptr_address"},
             {"ptr_from_address", "ptr_from_address"},
             {"ptr_offset", "ptr_offset"},
             {"ptr_add", "ptr_add"},
             {"ptr_sub", "ptr_sub"},
             {"ptr_diff", "ptr_diff"},
             {"map_file", "map_file"},
             {"unmap_file", "unmap_file"},
             {"memory_protect", "memory_protect"},
             {"bytes_read", "bytes_read"},
             {"bytes_write", "bytes_write"}}},
        {"std.v1.task",
            {{"spawn", "__spawn_task"},
             {"await", "__await_task"},
             {"sleep_ms", "sleep_ms"},
             {"monotonic", "monotonic_time"}}},
        {"std.v1.sync",
            {{"retry_call", "retry_call"},
             {"with_cleanup", "with_cleanup"}}},
        {"std.v1.time",
            {{"now", "time"},
             {"monotonic", "monotonic_time"},
             {"sleep", "sleep"},
             {"sleep_ms", "sleep_ms"},
             {"time_format", "time_format"}}},
    };
    return m;
}

inline std::string resolveStdlibModuleAlias(std::string name) {
    static const std::unordered_map<std::string, std::string> aliases = {
        {"std.math", "std.v1.math"},
        {"std.string", "std.v1.string"},
        {"std.bytes", "std.v1.bytes"},
        {"std.collections", "std.v1.collections"},
        {"std.fs", "std.v1.fs"},
        {"std.process", "std.v1.process"},
        {"std.net", "std.v1.net"},
        {"std.os", "std.v1.os"},
        {"std.signal", "std.v1.signal"},
        {"std.memory", "std.v1.memory"},
        {"std.task", "std.v1.task"},
        {"std.sync", "std.v1.sync"},
        {"std.time", "std.v1.time"},
    };
    auto it = aliases.find(name);
    if (it != aliases.end()) return it->second;
    return name;
}

} // namespace kern

#endif
